#  define __P(X) X
# define _SOCK_ADDR	struct sockaddr
#undef __cplusplus
#   define SM_DEAD(proto) proto
#   define SM_DEAD_D
#   define PRINTFLIKE(x,y)

#   define	__BEGIN_DECLS
#   define	__END_DECLS
#   define SCANFLIKE(x,y)

//typedef struct {} va_dcl;
#  define SM_RCSID(str)
#  define SM_IDSTR(id,str)

typedef struct {} fpos_t;
typedef struct {} FILE;
typedef struct {} size_t;
typedef struct {} va_list;
typedef struct {} off_t;
typedef struct {} ssize_t;
typedef struct {} __uint16_t;
typedef struct {} __uint32_t;
typedef struct {} __uint64_t;
typedef struct {} __int32_t;
typedef struct {} __DARWIN_NFDBITS;
typedef struct {} u_int32_t;
typedef struct {} __uint8_t;
typedef struct {} sa_family_t;
typedef struct {} _SS_PAD1SIZE;
typedef struct {} __int64_t;
typedef struct {} _SS_PAD2SIZE;
typedef struct {} socklen_t;
typedef struct {} in_addr_t;
typedef struct {} in_port_t;
typedef struct {} uint32_t;
typedef struct {} __darwin_size_t;
typedef struct {} __darwin_sigset_t;
typedef struct {} pthread_attr_t;
typedef struct {} pid_t;
typedef struct {} uid_t;
typedef struct {} siginfo_t;
typedef struct {} sigset_t;
typedef struct {} u_char;
typedef struct {} u_int16_t;
typedef struct {} ns_sect;
typedef struct {} u_int;
typedef struct {} u_long;
typedef struct {} u_short;
typedef struct {} res_send_qhook;
typedef struct {} res_send_rhook;
typedef struct {} int32_t;
typedef struct {} __darwin_rune_t;
typedef struct {} _RuneEntry;
typedef struct {} _RuneRange;
typedef struct {} _RuneCharClass;
typedef struct {} _RuneLocale;
typedef struct {} __darwin_ct_rune_t;
typedef struct {} HEADER;
typedef struct {} querybuf;
typedef struct {} mode_t;
typedef struct {} filesec_t;
typedef struct {} filesec_property_t;
typedef struct {} __darwin_time_t;
typedef struct {} __darwin_suseconds_t;
typedef struct {} rlim_t;
typedef struct {} id_t;
typedef struct {} idtype_t;
typedef struct {} div_t;
typedef struct {} ldiv_t;
typedef struct {} lldiv_t;
typedef struct {} wchar_t;
typedef struct {} dev_t;
typedef struct {} gid_t;
typedef struct {} useconds_t;
typedef struct {} fd_set;
typedef struct {} uuid_t;
typedef struct {} jmp_buf;
typedef struct {} sigjmp_buf;
typedef struct {} clock_t;
typedef struct {} time_t;
typedef struct {} SM_FILE_T;
typedef struct {} SM_ATOMIC_UINT_T;
typedef struct {} SM_DEBUG_T;
typedef struct {} SM_EXC_TYPE_T;
typedef struct {} SM_EXC_T;
typedef struct {} SM_VAL_T;
typedef struct {} SM_JMPBUF_T;
typedef struct {} SM_EXC_HANDLER_T;
typedef struct {} LONGLONG_T;
typedef struct {} ULONGLONG_T;
typedef struct {} SM_POOLLINK_T;
typedef struct {} SM_RPOOL_RFREE_T;
typedef struct {} SM_RESOURCE_T;
typedef struct {} SM_RLIST_T;
typedef struct {} SM_RPOOL_T;
typedef struct {} SM_RPOOL_ATTACH_T;
typedef struct {} pthread_t;
typedef struct {} stack_t;
typedef struct {} sigfunc_t;
typedef struct {} SM_EVENT;
typedef struct {} uuid_string_t;
typedef struct {} __darwin_va_list;
typedef struct {} ADDRESS;
typedef struct {} esmtp_args_F;
typedef struct {} BITMAP256;
typedef struct {} QPATHS;
typedef struct {} MACROS_T;
typedef struct {} HDR;
typedef struct {} ENVELOPE;
typedef struct {} ino_t;
typedef struct {} MAILER;
typedef struct {} HOSTSIG_T;
typedef struct {} QUEUEGRP;
typedef struct {} STAB;
typedef struct {} mi_int32;
typedef struct {} nlink_t;
typedef struct {} __DARWIN_STRUCT_STAT64;
typedef struct {} db_close_func;
typedef struct {} db_del_func;
typedef struct {} db_fd_func;
typedef struct {} db_get_func;
typedef struct {} db_put_func;
typedef struct {} db_sync_func;
typedef struct {} db_set_owner_func;
typedef struct {} db_cursor_func;
typedef struct {} db_lockfd_func;
typedef struct {} db_cursor_close_func;
typedef struct {} db_cursor_del_func;
typedef struct {} db_cursor_get_func;
typedef struct {} db_cursor_put_func;
typedef struct {} SMDB_DATABASE;
typedef struct {} SMDB_DBENT;
typedef struct {} SMDB_DBPARAMS;
typedef struct {} SMDB_USER_INFO;
typedef struct {} pthread_cond_t;
typedef struct {} pthread_condattr_t;
typedef struct {} pthread_mutex_t;
typedef struct {} pthread_key_t;
typedef struct {} pthread_mutexattr_t;
typedef struct {} pthread_once_t;
typedef struct {} pthread_rwlock_t;
typedef struct {} pthread_rwlockattr_t;
typedef struct {} mach_port_t;
typedef struct {} DBTYPE;
typedef struct {} DBT;
typedef struct {} DB;
typedef struct {} sthread_t;
typedef struct {} socket_t;
typedef struct {} smfiDesc_ptr;
typedef struct {} SMFICTX_PTR;
typedef struct {} cmdfct;
typedef struct {} sfsistat;
typedef struct {} genarg;
typedef struct {} SMFICTX;
typedef struct {} nfds_t;
typedef struct {} smutex_t;
typedef struct {} QUEUE_CHAR;
typedef struct {} MODE_T;
typedef struct {} smfiDesc_str;
typedef struct {} scond_t;
typedef struct {} smfi_hd_T;
typedef struct {} taskmgr_T;
typedef struct {} SM_ABORT_HANDLER_T;
#define MAP		struct _map

# define SM_IO_SET_TYPE(f, name, open, close, read, write, seek, get, set, timeout) \
    (f) = {SmFileMagic, (unsigned char *) 0, 0, 0, 0L, -1, {0}, 0, (void *) 0,\
	0, (close), (read), (seek), (write), (open), (set), (get), (timeout),\
	0, (name)}
# define SM_IO_INIT_TYPE(f, name, open, close, read, write, seek, get, set, timeout)

#define MCI		struct mailer_con_info

#  define GIDSET_T	int

typedef struct {} SM_CF_OPT_T;
typedef struct {} SM_DEBUG_SETTING_T;
typedef struct {} SM_DEBUG_UNKNOWN;
typedef struct {} BER_MEMALLOC_FN;
typedef struct {} BER_MEMCALLOC_FN;
typedef struct {} BER_MEMREALLOC_FN;
typedef struct {} BER_MEMFREE_FN;
typedef struct {} Sockbuf;
typedef struct {} Sockbuf_IO;
typedef struct {} Sockbuf_IO_Desc;
typedef struct {} ber_slen_t;
typedef struct {} ber_len_t;
typedef struct {} ldap_sync_search_entry_f;
typedef struct {} ldap_sync_search_reference_f;
typedef struct {} ldap_sync_intermediate_f;
typedef struct {} ldap_sync_search_result_f;
typedef struct {} LDAP;
typedef struct {} ldap_sync_refresh_t;
typedef struct {} ldap_conn_add_f;
typedef struct {} ldap_conn_del_f;
typedef struct {} ber_int_t;
typedef struct {} BerVarray;
typedef struct {} LDAPDerefVal;
typedef struct {} SM_EXC_DEFAULT_HANDLER_T;
typedef struct {} POS_ERR;
typedef struct {} SM_HEAP_ITEM_T;
typedef struct {} HEAP_CHECK;
typedef struct {} SM_LDAP_RECURSE_ENTRY;
typedef struct {} SM_LDAP_STRUCT;
typedef struct {} LDAPURLDesc;
typedef struct {} LDAPMessage;
typedef struct {} SM_LDAP_RECURSE_LIST;
typedef struct {} BerElement;
typedef struct {} SM_MBDB_TYPE_T;
typedef struct {} SM_MBDB_T;
typedef struct {} kstat_ctl_t;
typedef struct {} kstat_t;
typedef struct {} kstat_named_t;
typedef struct {} ni_status;
typedef struct {} ni_id;
typedef struct {} ni_namelist;
typedef struct {} SM_ALIGN_SIZE;
typedef struct {} SM_POOLHDR_T;
typedef struct {} ushort;
typedef struct {} key_t;
typedef struct {} SM_VA_LOCAL_DECL;
typedef struct {} SM_STR_OBJ_T;
typedef struct {} sm_qic_T;
typedef struct {} SMDB_DBTYPE;
typedef struct {} dbtype;
typedef struct {} SMDB_DB1_DATABASE;
typedef struct {} SMDB_FLAG;
typedef struct {} SMDB_CURSOR;
typedef struct {} SMDB_DB1_CURSOR;
typedef struct {} HASHINFO;
typedef struct {} BTREEINFO;
typedef struct {} SMDB_DB2_DATABASE;
typedef struct {} DBC;
typedef struct {} DBM;
typedef struct {} SMDB_DBM_DATABASE;
typedef struct {} datum;
typedef struct {} SMDB_DBM_CURSOR;
typedef struct {} bool;
typedef struct {} UID_T;
typedef struct {} GID_T;
typedef struct {} mkstemp;
typedef struct {} processor_set_t;
typedef struct {} kern_return_t;
typedef struct {} host_t;
typedef struct {} processor_set_info_t;
typedef struct {} caddr_t;
typedef struct {} status_$t;
typedef struct {} TIOCNOTTY;
typedef struct {} RLIM_INFINITY;
typedef struct {} u_int64_t;
typedef struct {} id;
typedef struct {} than;
typedef struct {} NOW;
typedef struct {} CRYPTO_EX_DATA;
typedef struct {} RAND_METHOD;
typedef struct {} ENGINE;
typedef struct {} n_long;
typedef struct {} DAEMON_T;
typedef struct {} log;
typedef struct {} error;
typedef struct {} INADDR_ANY;
typedef struct {} SOCKADDR;
typedef struct {} STACK;
typedef struct {} CRYPTO_EX_new;
typedef struct {} CRYPTO_EX_free;
typedef struct {} CRYPTO_EX_dup;
typedef struct {} CRYPTO_EX_DATA_IMPL;
typedef struct {} CRYPTO_MEM_LEAK_CB;
typedef struct {} BIO;
typedef struct {} bio_info_cb;
typedef struct {} BIO_METHOD;
typedef struct {} LHASH_NODE;
typedef struct {} LHASH_COMP_FN_TYPE;
typedef struct {} LHASH_HASH_FN_TYPE;
typedef struct {} LHASH;
typedef struct {} LHASH_DOALL_FN_TYPE;
typedef struct {} LHASH_DOALL_ARG_FN_TYPE;
typedef struct {} ERR_STRING_DATA;
typedef struct {} ERR_STATE;
typedef struct {} ERR_FNS;
typedef struct {} NULLADDR;
typedef struct {} SM_NO_UID;
typedef struct {} ARGCLASS_T;
typedef struct {} sasl_callback_t;
typedef struct {} nis_result;
typedef struct {} PH_MAP_STRUCT;
typedef struct {} regoff_t;
typedef struct {} regex_t;
typedef struct {} regmatch_t;
typedef struct {} ns_map_t;
typedef struct {} ns_map_list_t;
typedef struct {} __DARWIN_STRUCT_DIRENTRY;
typedef struct {} __darwin_pthread_mutex_t;
typedef struct {} DIR;
typedef struct {} milters_T;
typedef struct {} WORK;
typedef struct {} FILESYS;
typedef struct {} QUEUE_SHM_T;
typedef struct {} OPEN_TF;
typedef struct {} SM_T_SIZE;
typedef struct {} SEL_SHM_KEY;
typedef struct {} SORTQGRP_T;
typedef struct {} CTime_T;
typedef struct {} CHash_T;
typedef struct {} sortfn_t;
typedef struct {} SASL_AI_T;
typedef struct {} sasl_conn_t;
typedef struct {} SSL;
typedef struct {} TIMER;
typedef struct {} ARBPTR_T;
typedef struct {} PH;
typedef struct {} SIGFUNC_DECL;
typedef struct {} shmatt_t;
typedef struct {} STATUSD_SHM;
typedef struct {} STATUSD_SHM_KEY;
typedef struct {} MX_RECORD_T;
typedef struct {} SRV_RECORDT_T;
typedef struct {} RESOURCE_RECORD_T;
typedef struct {} DNS_QUERY_T;
typedef struct {} SSL_CTX;
typedef struct {} SMTP_T;
#define MAX_MACROS_ENTRIES	7
#  define SOCKADDR_LEN_T	int

#define va_dcl SM_VA_LOCAL_DECL

#define SM_TIME_IMMEDIATE	(0)
#define SM_TIME_FOREVER		(-1)
#define SM_TIME_DEFAULT		(-2)

# define SLEEP_T	unsigned int

#  define SM_NONVOLATILE


# define SM_VA_LOCAL_DECL	va_list ap;
#define MI_SUCCESS	0
#define MI_FAILURE	(-1)
#  define SM_VA_START(ap, f)	va_start(ap, f)

# define SM_VA_LOCAL_DECL	va_list ap;
# define SM_VA_ARG(ap, type)	va_arg(ap, type)
# define SM_VA_END(ap)		va_end(ap)
typedef struct {} must;
typedef struct {} be;
typedef struct {} sasl_al_properties_t;
typedef struct {} sasl_security_properties_t;
typedef struct {} sasl_ssf_t;
typedef struct {} BIGNUM;
typedef struct {} BN_GENCB;
typedef struct {} BN_CTX;
typedef struct {} BN_MONT_CTX;
typedef struct {} BN_BLINDING;
typedef struct {} BN_RECP_CTX;
typedef struct {} ASN1_BOOLEAN;
typedef struct {} ASN1_STRING;
typedef struct {} ASN1_OBJECT;
typedef struct {} ASN1_INTEGER;
typedef struct {} ASN1_ENUMERATED;
typedef struct {} ASN1_BIT_STRING;
typedef struct {} ASN1_OCTET_STRING;
typedef struct {} ASN1_PRINTABLESTRING;
typedef struct {} ASN1_T61STRING;
typedef struct {} ASN1_IA5STRING;
typedef struct {} ASN1_GENERALSTRING;
typedef struct {} ASN1_BMPSTRING;
typedef struct {} ASN1_UNIVERSALSTRING;
typedef struct {} ASN1_UTCTIME;
typedef struct {} ASN1_GENERALIZEDTIME;
typedef struct {} ASN1_VISIBLESTRING;
typedef struct {} ASN1_UTF8STRING;
typedef struct {} ASN1_VALUE;
typedef struct {} i2d_of_void;
typedef struct {} d2i_of_void;
typedef struct {} ASN1_METHOD;
typedef struct {} ASN1_TYPE;
typedef struct {} BIT_STRING_BITNAME;
typedef struct {} ASN1_TIME;
typedef struct {} ASN1_CTX;
typedef struct {} ASN1__CTX;
typedef struct {} ASN1_ITEM;
typedef struct {} ASN1_HEADER;
typedef struct {} ASN1_STRING_TABLE;
typedef struct {} CONF;
typedef struct {} X509V3_CTX;
typedef struct {} asn1_output_data_fn;
typedef struct {} OBJ_NAME;
typedef struct {} EVP_MD_CTX;
typedef struct {} EVP_MD;
typedef struct {} EVP_CIPHER_CTX;
typedef struct {} EVP_CIPHER;
typedef struct {} EVP_PKEY;
typedef struct {} EVP_ENCODE_CTX;
typedef struct {} EVP_PBE_KEYGEN;
typedef struct {} BUF_MEM;
typedef struct {} EC_METHOD;
typedef struct {} EC_GROUP;
typedef struct {} EC_POINT;
typedef struct {} point_conversion_form_t;
typedef struct {} EC_builtin_curve;
typedef struct {} EC_KEY;
typedef struct {} ECDSA_SIG;
typedef struct {} ECDSA_METHOD;
typedef struct {} ECDH_METHOD;
typedef struct {} RSA;
typedef struct {} RSA_METHOD;
typedef struct {} DH;
typedef struct {} DH_METHOD;
typedef struct {} DSA_SIG;
typedef struct {} DSA;
typedef struct {} DSA_METHOD;
typedef struct {} SHA_CTX;
typedef struct {} SHA256_CTX;
typedef struct {} SHA512_CTX;
typedef struct {} X509_ALGOR;
typedef struct {} ASN1_ENCODING;
typedef struct {} X509_NAME;
typedef struct {} X509_PUBKEY;
typedef struct {} X509_REQ_INFO;
typedef struct {} X509_VAL;
typedef struct {} X509_CINF;
typedef struct {} X509_POLICY_CACHE;
typedef struct {} X509_CERT_AUX;
typedef struct {} X509;
typedef struct {} X509_CRL_INFO;
typedef struct {} EVP_CIPHER_INFO;
typedef struct {} X509_CRL;
typedef struct {} X509_PKEY;
typedef struct {} NETSCAPE_SPKAC;
typedef struct {} X509_LOOKUP;
typedef struct {} X509_OBJECT;
typedef struct {} X509_VERIFY_PARAM;
typedef struct {} X509_STORE_CTX;
typedef struct {} X509_STORE;
typedef struct {} X509_LOOKUP_METHOD;
typedef struct {} X509_POLICY_TREE;
typedef struct {} X509_POLICY_LEVEL;
typedef struct {} X509_POLICY_NODE;
typedef struct {} PKCS7_ISSUER_AND_SERIAL;
typedef struct {} PKCS7_ENC_CONTENT;
typedef struct {} PKCS7_SIGNED;
typedef struct {} PKCS7_ENVELOPE;
typedef struct {} PKCS7_SIGN_ENVELOPE;
typedef struct {} PKCS7_DIGEST;
typedef struct {} PKCS7_ENCRYPT;
typedef struct {} PKCS7;
typedef struct {} PKCS7_SIGNER_INFO;
typedef struct {} PKCS7_RECIP_INFO;
typedef struct {} X509_REQ;
typedef struct {} NETSCAPE_SPKI;
typedef struct {} X509_SIG;
typedef struct {} PKCS8_PRIV_KEY_INFO;
typedef struct {} X509_ATTRIBUTE;
typedef struct {} X509_EXTENSION;
typedef struct {} X509_NAME_ENTRY;
typedef struct {} X509_REVOKED;
typedef struct {} X509_INFO;
typedef struct {} X509_TRUST;
typedef struct {} PEM_USER;
typedef struct {} pem_password_cb;
typedef struct {} PEM_ENCODE_SEAL_CTX;
typedef struct {} SSL_CIPHER;

#define MAPCLASS	struct _mapclass
#define MAP		struct _map
#define MAXMAPACTIONS	5

#  define SM_INT32	int32_t
#define EXTERN

typedef struct {} sasl_secret_t;
typedef struct {} sasl_interact_t;
typedef struct {} ARGV_T;
typedef struct {} PROCS_T;
typedef struct {} NO_PID;
typedef struct {} ALIAS;
typedef struct {} SYSLOG_T;
typedef struct {} INTERVAL_UNDEF;
typedef struct {} ONLY_ONCE;
typedef struct {} IGNORE_T;
